[package]
name = "scribium-markdown"
version = "0.0.1"
publish = false
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "Rushdown-backed Scribium Markdown frontend and Quarkdown adapter"

[dependencies]
rushdown.workspace = true
scribium-quarkdown.workspace = true
scribium-source.workspace = true

[dev-dependencies]
proptest = "1"
