[files]
extend-exclude = ["*.lock", "target/*"]

[default]
extend-ignore-re = [
    "LICENSE",
    "NOTICE",
]

[default.extend-words]
Scribium = "Scribium"
Quarkdown = "Quarkdown"
Typst = "Typst"
Markdown = "Markdown"
