[package]
name = "scribium-typst-subprocess"
version = "0.0.1"
publish = false
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "Native Typst CLI subprocess adapter for Scribium"

[dependencies]
scribium-project.workspace = true
scribium-typst.workspace = true
tempfile.workspace = true
typst-syntax.workspace = true

[dev-dependencies]
scribium-core.workspace = true
