[package]
name = "scribium-cli"
version = "0.0.1"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "Scribium CLI — build, check, inspect, and watch commands"

[features]
default = []
typst-inprocess = ["dep:scribium-typst-inprocess"]

[[bin]]
name = "scribium"
path = "src/main.rs"

[dependencies]
scribium-core.workspace = true
scribium-project.workspace = true
scribium-typst.workspace = true
scribium-typst-inprocess = { workspace = true, optional = true }
scribium-typst-subprocess.workspace = true
clap.workspace = true
anyhow.workspace = true
same-file.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile = "3.8"
