//! Typst lowering — converts the Scribium IR into Typst source code.
//!
//! Each IR node type maps to a Typst construct. The lowering pass
//! records source map entries as it generates code.

use scribium_core::ir::{
    IrCallSegment, IrDocument, IrInline, IrNode, IrTableAlignment, IrTableCell, IrTableRow,
    IrTaskStatus, IrValue, SourceMapEntry,
};
use scribium_core::source::SourceSpan;

/// Lower a Scribium IR document to Typst source code.
///
/// Returns the generated Typst source along with a source map that
/// links each generated byte range back to its original source span.
pub fn lower_to_typst(doc: &IrDocument) -> (String, Vec<SourceMapEntry>) {
    let mut ctx = LoweringContext::new();
    ctx.lower_document(doc);
    (ctx.output, ctx.source_map)
}

/// Lower a Scribium IR document to Typst source code without source map.
pub fn lower_to_typst_code(doc: &IrDocument) -> String {
    lower_to_typst(doc).0
}
struct LoweringContext {
    output: String,
    source_map: Vec<SourceMapEntry>,
    /// Current list nesting level (0 = top-level, 1 = nested, etc.)
    list_nesting: usize,
    /// Indentation string for the current list level (used for nested items)
    list_indent: String,
    /// Continuation indent for the list item currently being emitted.
    ///
    /// While non-empty, every newly started line is prefixed with this
    /// string so that all blocks of the current `IrListItem` stay contained
    /// in that item in the generated Typst (Typst list items own every line
    /// indented to at least the item's content column).
    list_item_indent: String,
    /// Whether line starts get the item continuation indent.
    at_line_start: bool,
    /// Whether the raw pushed text must not receive the continuation
    /// indent (verbatim code/raw content inside a list item).
    verbatim: bool,
}

impl LoweringContext {
    fn new() -> Self {
        Self {
            output: String::new(),
            source_map: Vec::new(),
            list_nesting: 0,
            list_indent: String::new(),
            list_item_indent: String::new(),
            at_line_start: false,
            verbatim: false,
        }
    }

    /// Record a source map entry for the generated range just produced.
    fn record_span(&mut self, original: SourceSpan, generated_len: usize) {
        let start = self.output.len().saturating_sub(generated_len);
        let end = self.output.len();
        if start < end {
            self.source_map.push(SourceMapEntry {
                generated_start: start,
                generated_end: end,
                original,
            });
        }
    }

    fn lower_document(&mut self, doc: &IrDocument) {
        // Emit metadata as Typst set-rules
        if let Some(ref title) = doc.metadata.title {
            self.push_str(&format!("// Title: {}\n", title));
        }
        if let Some(ref author) = doc.metadata.author {
            self.push_str(&format!("// Author: {}\n", author));
        }
        if let Some(ref date) = doc.metadata.date {
            self.push_str(&format!("// Date: {}\n", date));
        }

        for node in &doc.nodes {
            self.lower_node(node);
            self.push('\n');
        }
    }

    fn lower_node(&mut self, node: &IrNode) {
        match node {
            IrNode::Heading {
                level,
                content,
                span,
            } => {
                let prefix = "=".repeat(*level);
                let before = self.output.len();
                self.push_str(&prefix);
                self.push(' ');
                self.lower_inlines(content);
                self.push('\n');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::Paragraph { content, span } => {
                let before = self.output.len();
                self.lower_inlines(content);
                self.push('\n');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::Blockquote { content, span } => {
                let before = self.output.len();
                self.push_str("#quote(block: true)[\n");
                for child in content {
                    self.lower_node(child);
                }
                self.push_str("]\n");
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::UnorderedList { items, span } => {
                let before = self.output.len();
                let was_nested = self.list_nesting > 0;
                if was_nested {
                    self.list_indent.push_str("  ");
                }
                self.list_nesting += 1;
                for item in items {
                    let marker_prefix = if was_nested {
                        format!("{} - ", self.list_indent)
                    } else {
                        "- ".to_string()
                    };
                    self.lower_list_item(&marker_prefix, item);
                }
                self.list_nesting -= 1;
                if was_nested {
                    self.list_indent
                        .truncate(self.list_indent.len().saturating_sub(2));
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::OrderedList { items, start, span } => {
                let before = self.output.len();
                let was_nested = self.list_nesting > 0;
                if was_nested {
                    self.list_indent.push_str("  ");
                }
                self.list_nesting += 1;
                for (i, item) in items.iter().enumerate() {
                    let counter = start + i;
                    let marker_prefix = if was_nested {
                        format!("{}{}. ", self.list_indent, counter)
                    } else {
                        format!("{}. ", counter)
                    };
                    self.lower_list_item(&marker_prefix, item);
                }
                self.list_nesting -= 1;
                if was_nested {
                    self.list_indent
                        .truncate(self.list_indent.len().saturating_sub(2));
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::Table { header, rows, span } => {
                let before = self.output.len();
                self.lower_table(header, rows);
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::CodeBlock {
                language,
                source,
                span,
            } => {
                let before = self.output.len();
                self.push_str("```");
                if let Some(lang) = language {
                    self.push_str(lang);
                }
                self.push('\n');
                let was_verbatim = std::mem::replace(&mut self.verbatim, true);
                self.push_str(source);
                if !source.ends_with('\n') {
                    self.push('\n');
                }
                self.verbatim = was_verbatim;
                self.push_str("```\n");
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::RawTypst { source, span } => {
                let before = self.output.len();
                let was_verbatim = std::mem::replace(&mut self.verbatim, true);
                self.push_str(source);
                if !source.ends_with('\n') {
                    self.push('\n');
                }
                self.verbatim = was_verbatim;
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::FunctionCall {
                name,
                positional_args,
                named_args,
                body,
                span,
            } => {
                let before = self.output.len();
                self.push_str("#");
                self.push_str(name);
                if !positional_args.is_empty() || !named_args.is_empty() {
                    self.push('(');
                    let mut first = true;
                    for arg in positional_args {
                        if !first {
                            self.push_str(", ");
                        }
                        self.lower_value(arg);
                        first = false;
                    }
                    for (key, val) in named_args {
                        if !first {
                            self.push_str(", ");
                        }
                        self.push_str(key);
                        self.push_str(": ");
                        self.lower_value(val);
                        first = false;
                    }
                    self.push(')');
                }
                if let Some(body_nodes) = body {
                    self.push('[');
                    let saved_item = std::mem::take(&mut self.list_item_indent);
                    for node in body_nodes {
                        self.lower_node(node);
                    }
                    self.list_item_indent = saved_item;
                    self.push(']');
                }
                self.push('\n');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::ChainedFunctionCall {
                head,
                chain,
                body,
                span,
            } => {
                // Defensive rendering for manually constructed unresolved IR.
                // The normal evaluator resolves successful chains before this
                // lowering pass, and failed chains are rejected by diagnostics.
                let before = self.output.len();
                self.push_str("// Scribium parser-preserved call chain: ");
                self.lower_chain_label(head, chain);
                self.push_str(" (unresolved chain; evaluator did not resolve it)\n");
                if let Some(body_nodes) = body {
                    for node in body_nodes {
                        self.lower_node(node);
                    }
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::ThematicBreak { span } => {
                let before = self.output.len();
                self.push_str("---\n");
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::Math {
                source,
                display,
                span,
            } => {
                let before = self.output.len();
                if *display {
                    self.push_str("$ ");
                    self.push_str(source);
                    self.push_str(" $\n");
                } else {
                    self.push('$');
                    self.push_str(source);
                    self.push('$');
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
        }
    }

    fn lower_inlines(&mut self, inlines: &[IrInline]) {
        for inline in inlines {
            self.lower_inline(inline);
        }
    }

    fn lower_inline(&mut self, inline: &IrInline) {
        match inline {
            IrInline::Text { content, span } => {
                let before = self.output.len();
                self.push_str(content);
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::Emphasis { content, span } => {
                let before = self.output.len();
                self.push('*');
                self.lower_inlines(content);
                self.push('*');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::Strong { content, span } => {
                let before = self.output.len();
                self.push_str("*");
                self.lower_inlines(content);
                self.push_str("*");
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::Strikethrough { content, span } => {
                let before = self.output.len();
                self.push_str("#strike[");
                self.lower_inlines(content);
                self.push(']');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::DirectiveCall {
                name,
                positional_args,
                named_args,
                body,
                span,
            } => {
                let before = self.output.len();
                self.push_str("#");
                self.push_str(name);
                if !positional_args.is_empty() || !named_args.is_empty() {
                    self.push('(');
                    let mut first = true;
                    for arg in positional_args {
                        if !first {
                            self.push_str(", ");
                        }
                        self.lower_value(arg);
                        first = false;
                    }
                    for (key, val) in named_args {
                        if !first {
                            self.push_str(", ");
                        }
                        self.push_str(key);
                        self.push_str(": ");
                        self.lower_value(val);
                        first = false;
                    }
                    self.push(')');
                }
                if let Some(body_inlines) = body {
                    self.push('[');
                    self.lower_inlines(body_inlines);
                    self.push(']');
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::ChainedDirectiveCall {
                head,
                chain,
                body,
                span,
            } => {
                // Defensive rendering for manually constructed unresolved IR.
                // The normal evaluator resolves successful chains before this
                // lowering pass, and failed chains are rejected by diagnostics.
                let before = self.output.len();
                self.push_str("/* Scribium parser-preserved call chain: ");
                self.lower_chain_label(head, chain);
                self.push_str("; unresolved chain; evaluator did not resolve it */");
                if let Some(body_inlines) = body {
                    self.push('[');
                    self.lower_inlines(body_inlines);
                    self.push(']');
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::Link {
                content,
                destination,
                span,
            } => {
                let before = self.output.len();
                self.push_str("#link(");
                self.push('"');
                self.push_str(&escape_typst_string(destination));
                self.push('"');
                self.push(')');
                self.push('[');
                self.lower_inlines(content);
                self.push(']');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::Code { content, span } => {
                let before = self.output.len();
                self.push_str("#raw(");
                self.push('"');
                self.push_str(&escape_typst_string(content));
                self.push('"');
                self.push(')');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
        }
    }

    fn lower_value(&mut self, value: &IrValue) {
        match value {
            IrValue::String(s) => {
                // Escape Typst string characters
                let escaped = escape_typst_string(s);
                self.push('"');
                self.push_str(&escaped);
                self.push('"');
            }
            IrValue::Number(n) => {
                self.push_str(&n.to_string());
            }
            IrValue::Boolean(b) => {
                self.push_str(if *b { "true" } else { "false" });
            }
            IrValue::Identifier(id) => {
                // A bare identifier argument is emitted as a string literal so
                // the generated Typst always compiles. Semantic resolution
                // against a function signature is the evaluator's job.
                let escaped = escape_typst_string(id);
                self.push('"');
                self.push_str(&escaped);
                self.push('"');
            }
            IrValue::Content(nodes) => {
                self.push('[');
                let saved_item = std::mem::take(&mut self.list_item_indent);
                for node in nodes {
                    self.lower_node(node);
                }
                self.list_item_indent = saved_item;
                self.push(']');
            }
        }
    }

    fn lower_chain_label(&mut self, head: &IrCallSegment, chain: &[IrCallSegment]) {
        self.push('.');
        self.push_str(&head.name);
        for segment in chain {
            self.push_str("::");
            self.push_str(&segment.name);
        }
    }

    fn push(&mut self, ch: char) {
        if ch != '\n' {
            self.inject_item_indent();
        }
        self.output.push(ch);
        if ch == '\n' {
            self.at_line_start = true;
        }
    }

    fn push_str(&mut self, s: &str) {
        self.inject_item_indent();
        self.output.push_str(s);
        if s.ends_with('\n') {
            self.at_line_start = true;
        }
    }

    fn inject_item_indent(&mut self) {
        if self.at_line_start && !self.verbatim && !self.list_item_indent.is_empty() {
            self.output.push_str(&self.list_item_indent);
            self.at_line_start = false;
        }
    }

    /// Lower every block of the current `IrListItem` so the item's
    /// continuation indent is applied at each block boundary.
    fn lower_list_item(&mut self, marker_prefix: &str, item: &scribium_core::ir::IrListItem) {
        let before = self.output.len();
        let saved = std::mem::replace(&mut self.list_item_indent, " ".repeat(marker_prefix.len()));
        self.at_line_start = false;
        self.push_str(marker_prefix);
        if let Some(task) = item.task {
            self.push_str(match task {
                IrTaskStatus::Active => "☐ ",
                IrTaskStatus::Completed => "☑ ",
            });
        }
        for child in &item.nodes {
            self.lower_item_block(child);
        }
        self.list_item_indent = saved;
        self.push('\n');
        if item.span.source_id != scribium_core::SourceId(0) {
            self.record_span(item.span, self.output.len() - before);
        }
    }

    fn lower_table(&mut self, header: &IrTableRow, rows: &[IrTableRow]) {
        let columns = header
            .cells
            .len()
            .max(rows.iter().map(|row| row.cells.len()).max().unwrap_or(0))
            .max(1);
        self.push_str("#table(\n");
        self.push_str(&format!("  columns: {columns},\n"));
        let header_before = self.output.len();
        self.push_str("  table.header(");
        self.lower_table_cells(&header.cells, columns);
        self.push_str("),\n");
        if header.span.source_id != scribium_core::SourceId(0) {
            self.record_span(header.span, self.output.len() - header_before);
        }
        for row in rows {
            let row_before = self.output.len();
            self.push_str("  ");
            self.lower_table_cells(&row.cells, columns);
            self.push_str(",\n");
            if row.span.source_id != scribium_core::SourceId(0) {
                self.record_span(row.span, self.output.len() - row_before);
            }
        }
        self.push_str(")\n");
    }

    fn lower_table_cells(&mut self, cells: &[IrTableCell], columns: usize) {
        for index in 0..columns {
            if index > 0 {
                self.push_str(", ");
            }
            if let Some(cell) = cells.get(index) {
                self.lower_table_cell(cell);
            } else {
                self.push_str("table.cell(align: auto)[]");
            }
        }
    }

    fn lower_table_cell(&mut self, cell: &IrTableCell) {
        let before = self.output.len();
        self.push_str("table.cell(align: ");
        self.push_str(table_alignment_name(cell.alignment));
        self.push_str(")[");
        self.lower_inlines(&cell.content);
        self.push(']');
        if cell.span.source_id != scribium_core::SourceId(0) {
            self.record_span(cell.span, self.output.len() - before);
        }
    }

    fn lower_item_block(&mut self, node: &IrNode) {
        match node {
            // Nested lists carry their own indentation (`list_indent`), so
            // the item continuation indent must not be re-applied to them.
            IrNode::UnorderedList { .. } | IrNode::OrderedList { .. } => {
                let saved = std::mem::take(&mut self.list_item_indent);
                self.lower_node(node);
                self.list_item_indent = saved;
            }
            _ => self.lower_node(node),
        }
    }
}

fn table_alignment_name(alignment: IrTableAlignment) -> &'static str {
    match alignment {
        IrTableAlignment::Left => "left",
        IrTableAlignment::Center => "center",
        IrTableAlignment::Right => "right",
        IrTableAlignment::None => "auto",
    }
}

/// Escape characters that are special inside a double-quoted Typst string:
/// backslashes and double quotes.
fn escape_typst_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use scribium_core::ir::{
        IrCallSegment, IrDocument, IrInline, IrListItem, IrMetadata, IrNode, IrTableAlignment,
        IrTableCell, IrTableRow, IrTaskStatus, IrValue,
    };
    use scribium_core::source::SourceSpan;

    fn empty_span() -> SourceSpan {
        SourceSpan::new(scribium_core::SourceId(0), 0, 0)
    }

    fn text(text: &str) -> IrInline {
        IrInline::Text {
            content: text.to_string(),
            span: empty_span(),
        }
    }

    #[test]
    fn lower_empty_document() {
        let doc = IrDocument {
            nodes: vec![],
            metadata: IrMetadata::default(),
        };
        let (code, map) = super::lower_to_typst(&doc);
        assert_eq!(code, "");
        assert!(map.is_empty());
    }

    #[test]
    fn lower_heading_paragraph() {
        let doc = IrDocument {
            nodes: vec![
                IrNode::Heading {
                    level: 1,
                    content: vec![text("Hello")],
                    span: empty_span(),
                },
                IrNode::Paragraph {
                    content: vec![text("World")],
                    span: empty_span(),
                },
            ],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "= Hello\n\nWorld\n\n");
    }

    #[test]
    fn lower_heading_levels() {
        let doc = IrDocument {
            nodes: vec![
                IrNode::Heading {
                    level: 2,
                    content: vec![text("Section")],
                    span: empty_span(),
                },
                IrNode::Heading {
                    level: 3,
                    content: vec![text("Subsection")],
                    span: empty_span(),
                },
            ],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "== Section\n\n=== Subsection\n\n");
    }

    #[test]
    fn lower_emphasis_and_strong() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![
                    text("Hello "),
                    IrInline::Emphasis {
                        content: vec![text("italic")],
                        span: empty_span(),
                    },
                    text(" and "),
                    IrInline::Strong {
                        content: vec![text("bold")],
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "Hello *italic* and *bold*\n\n");
    }

    #[test]
    fn lower_structured_markdown_nodes_preserves_semantics_and_source_map() {
        let quote_span = SourceSpan::new(scribium_core::SourceId(1), 0, 30);
        let strike_span = SourceSpan::new(scribium_core::SourceId(1), 8, 22);
        let active_span = SourceSpan::new(scribium_core::SourceId(1), 31, 45);
        let completed_span = SourceSpan::new(scribium_core::SourceId(1), 46, 62);
        let header_span = SourceSpan::new(scribium_core::SourceId(1), 64, 82);
        let row_span = SourceSpan::new(scribium_core::SourceId(1), 83, 98);
        let table_span = SourceSpan::new(scribium_core::SourceId(1), 64, 98);
        let doc = IrDocument {
            nodes: vec![
                IrNode::Blockquote {
                    content: vec![IrNode::Paragraph {
                        content: vec![IrInline::Strikethrough {
                            content: vec![IrInline::Strong {
                                content: vec![text("removed")],
                                span: strike_span,
                            }],
                            span: strike_span,
                        }],
                        span: quote_span,
                    }],
                    span: quote_span,
                },
                IrNode::UnorderedList {
                    items: vec![
                        IrListItem {
                            nodes: vec![
                                IrNode::Paragraph {
                                    content: vec![text("active")],
                                    span: active_span,
                                },
                                IrNode::UnorderedList {
                                    items: vec![IrListItem {
                                        nodes: vec![IrNode::Paragraph {
                                            content: vec![text("nested")],
                                            span: active_span,
                                        }],
                                        task: Some(IrTaskStatus::Completed),
                                        span: active_span,
                                    }],
                                    span: active_span,
                                },
                            ],
                            task: Some(IrTaskStatus::Active),
                            span: active_span,
                        },
                        IrListItem {
                            nodes: vec![IrNode::Paragraph {
                                content: vec![text("completed")],
                                span: completed_span,
                            }],
                            task: Some(IrTaskStatus::Completed),
                            span: completed_span,
                        },
                    ],
                    span: active_span,
                },
                IrNode::Table {
                    header: IrTableRow {
                        cells: vec![
                            IrTableCell {
                                content: vec![text("left")],
                                alignment: IrTableAlignment::Left,
                                span: header_span,
                            },
                            IrTableCell {
                                content: vec![text("center")],
                                alignment: IrTableAlignment::Center,
                                span: header_span,
                            },
                        ],
                        span: header_span,
                    },
                    rows: vec![IrTableRow {
                        cells: vec![IrTableCell {
                            content: vec![text("right")],
                            alignment: IrTableAlignment::Right,
                            span: row_span,
                        }],
                        span: row_span,
                    }],
                    span: table_span,
                },
            ],
            metadata: IrMetadata::default(),
        };

        let (code, map) = super::lower_to_typst(&doc);
        assert!(code.contains("#quote(block: true)["));
        assert!(code.contains("#strike[*removed*]"));
        assert!(code.contains("- ☐ active"));
        assert!(code.contains("- ☑ completed"));
        assert!(code.contains("☑ nested"));
        assert!(code.contains("columns: 2"));
        assert!(code.contains("align: left"));
        assert!(code.contains("align: center"));
        assert!(code.contains("align: right"));
        assert!(code.contains("table.cell(align: auto)[]"));
        assert!(map.iter().any(|entry| entry.original == quote_span));
        assert!(map.iter().any(|entry| entry.original == strike_span));
        assert!(map.iter().any(|entry| entry.original == active_span));
        assert!(map.iter().any(|entry| entry.original == completed_span));
        assert!(map.iter().any(|entry| entry.original == table_span));
        assert!(map
            .iter()
            .all(|entry| entry.generated_start < entry.generated_end
                && entry.generated_end <= code.len()));
    }

    #[test]
    fn lower_link() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![IrInline::Link {
                    content: vec![text("Example")],
                    destination: "https://example.com".into(),
                    span: empty_span(),
                }],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "#link(\"https://example.com\")[Example]\n\n");
    }

    #[test]
    fn lower_link_with_rich_label() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![IrInline::Link {
                    content: vec![IrInline::Strong {
                        content: vec![text("Bold")],
                        span: empty_span(),
                    }],
                    destination: "https://example.com".into(),
                    span: empty_span(),
                }],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "#link(\"https://example.com\")[*Bold*]\n\n");
    }

    #[test]
    fn link_escapes_special_characters_in_destination() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![IrInline::Link {
                    content: vec![text("x")],
                    destination: "https://example.com/a\\b\"c".into(),
                    span: empty_span(),
                }],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "#link(\"https://example.com/a\\\\b\\\"c\")[x]\n\n");
    }

    #[test]
    fn link_records_source_map_entry() {
        use scribium_core::ir::SourceMapEntry;

        let link_span = SourceSpan::new(scribium_core::SourceId(1), 6, 32);
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![IrInline::Link {
                    content: vec![text("Example")],
                    destination: "https://example.com".into(),
                    span: link_span,
                }],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let (code, map) = super::lower_to_typst(&doc);
        assert_eq!(code, "#link(\"https://example.com\")[Example]\n\n");
        assert_eq!(
            map,
            vec![SourceMapEntry {
                generated_start: 0,
                generated_end: 37,
                original: link_span,
            }]
        );
    }

    #[test]
    fn end_to_end_link_compiles_to_typst_link() {
        use scribium_core::{compile, CompileOptions, VirtualProjectBuilder};

        let source =
            "# Links\n\nVisit [Typst](https://typst.app).\n\nThis is a [**bold link**](https://example.com).\n";
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", source)
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        assert!(result.diagnostics.is_empty());
        let code = super::lower_to_typst_code(&result.ir);
        assert!(code.contains("#link(\"https://typst.app\")[Typst]"));
        assert!(code.contains("#link(\"https://example.com\")[*bold link*]"));
    }

    #[test]
    fn lower_code_span() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![
                    text("Run "),
                    IrInline::Code {
                        content: "cargo test".into(),
                        span: empty_span(),
                    },
                    text(" now"),
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "Run #raw(\"cargo test\") now\n\n");
    }

    #[test]
    fn code_span_keeps_typst_sensitive_characters_literal() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![IrInline::Code {
                    content: "a\"b\\c ` backtick #hash $dollar [b] {x} 한글".into(),
                    span: empty_span(),
                }],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        // Only `\` and `"` need escaping inside the string argument; the
        // rest stays literal inside #raw(...).
        assert_eq!(
            code,
            "#raw(\"a\\\"b\\\\c ` backtick #hash $dollar [b] {x} 한글\")\n\n"
        );
    }

    #[test]
    fn code_span_records_source_map_entry() {
        use scribium_core::ir::SourceMapEntry;

        let code_span = SourceSpan::new(scribium_core::SourceId(1), 7, 13);
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![IrInline::Code {
                    content: "foo".into(),
                    span: code_span,
                }],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let (code, map) = super::lower_to_typst(&doc);
        assert_eq!(code, "#raw(\"foo\")\n\n");
        assert_eq!(
            map,
            vec![SourceMapEntry {
                generated_start: 0,
                generated_end: 11,
                original: code_span,
            }]
        );
    }

    #[test]
    fn end_to_end_code_span_compiles_to_typst_raw() {
        use scribium_core::{compile, CompileOptions, VirtualProjectBuilder};

        let source = "# Code\n\nRun `cargo run`.\n\nUse ``foo ` bar`` when discussing backticks.\n\nLiteral syntax: `**not bold**`.\n";
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", source)
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        assert!(result.diagnostics.is_empty());
        let code = super::lower_to_typst_code(&result.ir);
        assert!(code.contains("#raw(\"cargo run\")"));
        assert!(code.contains("#raw(\"foo ` bar\")"));
        assert!(code.contains("#raw(\"**not bold**\")"));
        assert!(!code.contains("#link("));
    }

    #[test]
    fn lower_code_block() {
        let doc = IrDocument {
            nodes: vec![IrNode::CodeBlock {
                language: Some("rust".into()),
                source: "fn main() {}".into(),
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "```rust\nfn main() {}\n```\n\n");
    }

    #[test]
    fn lower_unordered_list() {
        let doc = IrDocument {
            nodes: vec![IrNode::UnorderedList {
                items: vec![
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("Item one")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("Item two")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "- Item one\n\n- Item two\n\n\n");
    }

    #[test]
    fn lower_ordered_list() {
        let doc = IrDocument {
            nodes: vec![IrNode::OrderedList {
                items: vec![
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("Item one")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("Item two")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                ],
                start: 1,
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "1. Item one\n\n2. Item two\n\n\n");
    }

    #[test]
    fn lower_ordered_list_non_one_start() {
        let doc = IrDocument {
            nodes: vec![IrNode::OrderedList {
                items: vec![
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("Item three")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("Item four")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                ],
                start: 3,
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "3. Item three\n\n4. Item four\n\n\n");
    }

    #[test]
    fn lower_nested_ordered_list() {
        let doc = IrDocument {
            nodes: vec![IrNode::OrderedList {
                items: vec![IrListItem {
                    nodes: vec![
                        IrNode::Paragraph {
                            content: vec![text("Outer")],
                            span: empty_span(),
                        },
                        IrNode::OrderedList {
                            items: vec![IrListItem {
                                nodes: vec![IrNode::Paragraph {
                                    content: vec![text("Inner")],
                                    span: empty_span(),
                                }],
                                task: None,
                                span: empty_span(),
                            }],
                            start: 1,
                            span: empty_span(),
                        },
                    ],
                    task: None,
                    span: empty_span(),
                }],
                start: 1,
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        // Paragraph "Outer" produces "Outer\n", nested list is indented with 2 spaces
        assert_eq!(code, "1. Outer\n  1. Inner\n\n\n\n");
    }

    #[test]
    fn lower_ordered_list_with_nested_unordered() {
        let doc = IrDocument {
            nodes: vec![IrNode::OrderedList {
                items: vec![IrListItem {
                    nodes: vec![
                        IrNode::Paragraph {
                            content: vec![text("ordered")],
                            span: empty_span(),
                        },
                        IrNode::UnorderedList {
                            items: vec![
                                IrListItem {
                                    nodes: vec![IrNode::Paragraph {
                                        content: vec![text("unordered")],
                                        span: empty_span(),
                                    }],
                                    task: None,
                                    span: empty_span(),
                                },
                                IrListItem {
                                    nodes: vec![IrNode::Paragraph {
                                        content: vec![text("another")],
                                        span: empty_span(),
                                    }],
                                    task: None,
                                    span: empty_span(),
                                },
                            ],
                            span: empty_span(),
                        },
                    ],
                    task: None,
                    span: empty_span(),
                }],
                start: 1,
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        // The nested unordered list stays inside the ordered item, indented
        // (marker format for nested items is `indent + " - "`)
        assert_eq!(code, "1. ordered\n   - unordered\n\n   - another\n\n\n\n");
    }

    #[test]
    fn lower_unordered_list_with_nested_ordered() {
        let doc = IrDocument {
            nodes: vec![IrNode::UnorderedList {
                items: vec![IrListItem {
                    nodes: vec![
                        IrNode::Paragraph {
                            content: vec![text("unordered")],
                            span: empty_span(),
                        },
                        IrNode::OrderedList {
                            items: vec![
                                IrListItem {
                                    nodes: vec![IrNode::Paragraph {
                                        content: vec![text("ordered")],
                                        span: empty_span(),
                                    }],
                                    task: None,
                                    span: empty_span(),
                                },
                                IrListItem {
                                    nodes: vec![IrNode::Paragraph {
                                        content: vec![text("ordered two")],
                                        span: empty_span(),
                                    }],
                                    task: None,
                                    span: empty_span(),
                                },
                            ],
                            start: 1,
                            span: empty_span(),
                        },
                    ],
                    task: None,
                    span: empty_span(),
                }],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        // Nested ordered list stays inside the parent item, indented by 2 spaces
        assert_eq!(
            code,
            "- unordered\n  1. ordered\n\n  2. ordered two\n\n\n\n"
        );
    }

    #[test]
    fn end_to_end_nested_ordered_list() {
        use scribium_core::{compile, CompileOptions, VirtualProjectBuilder};

        // Real Markdown source with a nested ordered list inside a parent item.
        // The inner list uses the parent's content column, the second item
        // "2. sibling" is a top-level sibling of the first one.
        let source = "1. parent\n    1. child\n    2. child2\n2. sibling\n";
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", source)
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        assert!(result.diagnostics.is_empty());
        let code = super::lower_to_typst_code(&result.ir);
        // The nested list must be indented inside the first item and must not
        // be flattened into top-level items.
        assert_eq!(
            code,
            "1. parent\n  1. child\n\n  2. child2\n\n\n2. sibling\n\n\n"
        );
    }

    // Regression: a list item may contain several block nodes, and every
    // block must stay structurally inside its item in the generated Typst.
    // The fence lines of the code block must be emitted at the item's
    // content column (marker width), while the verbatim body must not be
    // re-indented.

    #[test]
    fn lower_ordered_list_item_with_code_block() {
        let doc = IrDocument {
            nodes: vec![IrNode::OrderedList {
                start: 1,
                items: vec![
                    IrListItem {
                        nodes: vec![
                            IrNode::Paragraph {
                                content: vec![text("item")],
                                span: empty_span(),
                            },
                            IrNode::CodeBlock {
                                language: None,
                                source: "code".into(),
                                span: empty_span(),
                            },
                        ],
                        task: None,
                        span: empty_span(),
                    },
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("next")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "1. item\n   ```\ncode\n   ```\n\n2. next\n\n\n");
    }

    #[test]
    fn lower_unordered_list_item_with_code_block() {
        let doc = IrDocument {
            nodes: vec![IrNode::UnorderedList {
                items: vec![
                    IrListItem {
                        nodes: vec![
                            IrNode::Paragraph {
                                content: vec![text("item")],
                                span: empty_span(),
                            },
                            IrNode::CodeBlock {
                                language: None,
                                source: "code".into(),
                                span: empty_span(),
                            },
                        ],
                        task: None,
                        span: empty_span(),
                    },
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("next")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "- item\n  ```\ncode\n  ```\n\n- next\n\n\n");
    }

    #[test]
    fn lower_list_item_with_many_blocks_stays_contained() {
        let doc = IrDocument {
            nodes: vec![IrNode::OrderedList {
                start: 1,
                items: vec![
                    IrListItem {
                        nodes: vec![
                            IrNode::Paragraph {
                                content: vec![text("one")],
                                span: empty_span(),
                            },
                            IrNode::CodeBlock {
                                language: None,
                                source: "code".into(),
                                span: empty_span(),
                            },
                            IrNode::Paragraph {
                                content: vec![text("two")],
                                span: empty_span(),
                            },
                        ],
                        task: None,
                        span: empty_span(),
                    },
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("three")],
                            span: empty_span(),
                        }],
                        task: None,
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(
            code,
            "1. one\n   ```\ncode\n   ```\n   two\n\n2. three\n\n\n"
        );
    }

    #[test]
    fn lower_thematic_break() {
        let doc = IrDocument {
            nodes: vec![IrNode::ThematicBreak { span: empty_span() }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "---\n\n");
    }

    #[test]
    fn lower_inline_directive_call() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![
                    text("Look: "),
                    IrInline::DirectiveCall {
                        name: "strong".into(),
                        positional_args: vec![],
                        named_args: vec![],
                        body: Some(vec![text("emphasized")]),
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "Look: #strong[emphasized]\n\n");
    }

    #[test]
    fn lower_block_directive_call() {
        let doc = IrDocument {
            nodes: vec![IrNode::FunctionCall {
                name: "figure".into(),
                positional_args: vec![],
                named_args: vec![("kind".into(), IrValue::String("table".into()))],
                body: Some(vec![IrNode::Paragraph {
                    content: vec![text("content")],
                    span: empty_span(),
                }]),
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "#figure(kind: \"table\")[content\n]\n\n");
    }

    #[test]
    fn debug_render_parser_preserved_chain_after_semantic_gate() {
        let source_id = scribium_core::SourceId(7);
        let whole = SourceSpan::new(source_id, 0, 13);
        let doc = IrDocument {
            nodes: vec![IrNode::ChainedFunctionCall {
                head: IrCallSegment {
                    name: "a".into(),
                    name_span: SourceSpan::new(source_id, 0, 2),
                    positional_args: vec![],
                    named_args: vec![],
                    span: SourceSpan::new(source_id, 0, 6),
                },
                chain: vec![IrCallSegment {
                    name: "b".into(),
                    name_span: SourceSpan::new(source_id, 8, 9),
                    positional_args: vec![],
                    named_args: vec![],
                    span: SourceSpan::new(source_id, 8, 13),
                }],
                body: None,
                span: whole,
            }],
            metadata: IrMetadata::default(),
        };
        let (code, map) = super::lower_to_typst(&doc);
        assert_eq!(
            code,
            "// Scribium parser-preserved call chain: .a::b (unresolved chain; evaluator did not resolve it)\n\n"
        );
        assert_eq!(map.len(), 1);
        assert_eq!(map[0].original, whole);
        assert!(map[0].generated_end <= code.len());
    }

    #[test]
    fn lower_math_inline() {
        let doc = IrDocument {
            nodes: vec![IrNode::Math {
                source: "E = mc^2".into(),
                display: false,
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "$E = mc^2$\n");
    }

    #[test]
    fn lower_math_display() {
        let doc = IrDocument {
            nodes: vec![IrNode::Math {
                source: "x = (-b pm sqrt(b^2 - 4ac)) / (2a)".into(),
                display: true,
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "$ x = (-b pm sqrt(b^2 - 4ac)) / (2a) $\n\n");
    }
    #[test]
    fn source_map_is_independent_of_source_insertion_order() {
        use scribium_core::{compile, CompileOptions, VirtualProjectBuilder};

        let project1 = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("a.qd", "content a")
            .expect("valid path")
            .add_source("b.qd", "content b")
            .expect("valid path")
            .add_source("main.qd", "# Main\n\n{{ a.qd }} {{ b.qd }}")
            .expect("valid path")
            .build()
            .unwrap();

        let project2 = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("b.qd", "content b")
            .expect("valid path")
            .add_source("a.qd", "content a")
            .expect("valid path")
            .add_source("main.qd", "# Main\n\n{{ a.qd }} {{ b.qd }}")
            .expect("valid path")
            .build()
            .unwrap();

        let result1 = compile(&project1, &CompileOptions::default());
        let result2 = compile(&project2, &CompileOptions::default());

        // Lower to Typst with source maps
        let (typst1, map1) = super::lower_to_typst(&result1.ir);
        let (typst2, map2) = super::lower_to_typst(&result2.ir);

        // Generated Typst should be identical
        assert_eq!(typst1, typst2);

        // Source maps should be identical
        assert_eq!(map1, map2);
    }

    #[test]
    fn conditional_evaluation_before_lowering() {
        use crate::lower_to_typst_code;
        use scribium_core::{compile, CompileOptions, VirtualProjectBuilder};

        // .if {true} block body -> kept, no #if in output
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", ".if {true}\n    kept\n")
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        let typst = lower_to_typst_code(&result.ir);
        assert!(result.diagnostics.is_empty());
        assert!(typst.contains("kept"));
        assert!(!typst.contains("#if"));

        // .if {false} -> dropped
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", ".if {false}\n    dropped\n")
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        let typst = lower_to_typst_code(&result.ir);
        assert!(result.diagnostics.is_empty());
        assert!(!typst.contains("dropped"));

        // .ifnot {no} -> kept
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", ".ifnot {no}\n    kept\n")
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        let typst = lower_to_typst_code(&result.ir);
        assert!(result.diagnostics.is_empty());
        assert!(typst.contains("kept"));

        // Inline .if {true} {text}
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", "before .if {true} {inline} after\n")
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        let typst = lower_to_typst_code(&result.ir);
        assert!(result.diagnostics.is_empty());
        assert!(typst.contains("before"));
        assert!(typst.contains("inline"));
        assert!(typst.contains("after"));
        assert!(!typst.contains("#if"));
    }
}
