//! Typst lowering — converts the Scribium IR into Typst source code.
//!
//! Each IR node type maps to a Typst construct. The lowering pass
//! records source map entries as it generates code.

use scribium_core::ir::{IrDocument, IrInline, IrNode, IrValue, SourceMapEntry};
use scribium_core::source::SourceSpan;

/// Lower a Scribium IR document to Typst source code.
///
/// Returns the generated Typst source along with a source map that
/// links each generated byte range back to its original source span.
pub fn lower_to_typst(doc: &IrDocument) -> (String, Vec<SourceMapEntry>) {
    let mut ctx = LoweringContext::new();
    ctx.lower_document(doc);
    (ctx.output, ctx.source_map)
}

/// Lower a Scribium IR document to Typst source code without source map.
pub fn lower_to_typst_code(doc: &IrDocument) -> String {
    lower_to_typst(doc).0
}

struct LoweringContext {
    output: String,
    source_map: Vec<SourceMapEntry>,
}

impl LoweringContext {
    fn new() -> Self {
        Self {
            output: String::new(),
            source_map: Vec::new(),
        }
    }

    /// Record a source map entry for the generated range just produced.
    fn record_span(&mut self, original: SourceSpan, generated_len: usize) {
        let start = self.output.len().saturating_sub(generated_len);
        let end = self.output.len();
        if start < end {
            self.source_map.push(SourceMapEntry {
                generated_start: start,
                generated_end: end,
                original,
            });
        }
    }

    fn lower_document(&mut self, doc: &IrDocument) {
        // Emit metadata as Typst set-rules
        if let Some(ref title) = doc.metadata.title {
            self.push_str(&format!("// Title: {}\n", title));
        }
        if let Some(ref author) = doc.metadata.author {
            self.push_str(&format!("// Author: {}\n", author));
        }
        if let Some(ref date) = doc.metadata.date {
            self.push_str(&format!("// Date: {}\n", date));
        }

        for node in &doc.nodes {
            self.lower_node(node);
            self.push('\n');
        }
    }

    fn lower_node(&mut self, node: &IrNode) {
        match node {
            IrNode::Heading {
                level,
                content,
                span,
            } => {
                let prefix = "=".repeat(*level);
                let before = self.output.len();
                self.push_str(&prefix);
                self.push(' ');
                self.lower_inlines(content);
                self.push('\n');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::Paragraph { content, span } => {
                let before = self.output.len();
                self.lower_inlines(content);
                self.push('\n');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::UnorderedList { items, span } => {
                let before = self.output.len();
                for item in items {
                    self.push_str("- ");
                    for child in &item.nodes {
                        self.lower_node(child);
                    }
                    self.push('\n');
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::CodeBlock {
                language,
                source,
                span,
            } => {
                let before = self.output.len();
                self.push_str("```");
                if let Some(lang) = language {
                    self.push_str(lang);
                }
                self.push('\n');
                self.push_str(source);
                if !source.ends_with('\n') {
                    self.push('\n');
                }
                self.push_str("```\n");
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::RawTypst { source, span } => {
                let before = self.output.len();
                self.push_str(source);
                if !source.ends_with('\n') {
                    self.push('\n');
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::FunctionCall {
                name,
                positional_args,
                named_args,
                body,
                span,
            } => {
                let before = self.output.len();
                self.push_str("#");
                self.push_str(name);
                if !positional_args.is_empty() || !named_args.is_empty() {
                    self.push('(');
                    let mut first = true;
                    for arg in positional_args {
                        if !first {
                            self.push_str(", ");
                        }
                        self.lower_value(arg);
                        first = false;
                    }
                    for (key, val) in named_args {
                        if !first {
                            self.push_str(", ");
                        }
                        self.push_str(key);
                        self.push_str(": ");
                        self.lower_value(val);
                        first = false;
                    }
                    self.push(')');
                }
                if let Some(body_nodes) = body {
                    self.push('[');
                    for node in body_nodes {
                        self.lower_node(node);
                    }
                    self.push(']');
                }
                self.push('\n');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::ThematicBreak { span } => {
                let before = self.output.len();
                self.push_str("---\n");
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrNode::Math {
                source,
                display,
                span,
            } => {
                let before = self.output.len();
                if *display {
                    self.push_str("$ ");
                    self.push_str(source);
                    self.push_str(" $\n");
                } else {
                    self.push('$');
                    self.push_str(source);
                    self.push('$');
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
        }
    }

    fn lower_inlines(&mut self, inlines: &[IrInline]) {
        for inline in inlines {
            self.lower_inline(inline);
        }
    }

    fn lower_inline(&mut self, inline: &IrInline) {
        match inline {
            IrInline::Text { content, span } => {
                let before = self.output.len();
                self.push_str(content);
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::Emphasis { content, span } => {
                let before = self.output.len();
                self.push('*');
                self.lower_inlines(content);
                self.push('*');
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::Strong { content, span } => {
                let before = self.output.len();
                self.push_str("*");
                self.lower_inlines(content);
                self.push_str("*");
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
            IrInline::DirectiveCall {
                name,
                positional_args,
                named_args,
                body,
                span,
            } => {
                let before = self.output.len();
                self.push_str("#");
                self.push_str(name);
                if !positional_args.is_empty() || !named_args.is_empty() {
                    self.push('(');
                    let mut first = true;
                    for arg in positional_args {
                        if !first {
                            self.push_str(", ");
                        }
                        self.lower_value(arg);
                        first = false;
                    }
                    for (key, val) in named_args {
                        if !first {
                            self.push_str(", ");
                        }
                        self.push_str(key);
                        self.push_str(": ");
                        self.lower_value(val);
                        first = false;
                    }
                    self.push(')');
                }
                if let Some(body_inlines) = body {
                    self.push('[');
                    self.lower_inlines(body_inlines);
                    self.push(']');
                }
                if span.source_id != scribium_core::SourceId(0) {
                    self.record_span(*span, self.output.len() - before);
                }
            }
        }
    }

    fn lower_value(&mut self, value: &IrValue) {
        match value {
            IrValue::String(s) => {
                // Escape Typst string characters
                let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
                self.push('"');
                self.push_str(&escaped);
                self.push('"');
            }
            IrValue::Number(n) => {
                self.push_str(&n.to_string());
            }
            IrValue::Boolean(b) => {
                self.push_str(if *b { "true" } else { "false" });
            }
            IrValue::Identifier(id) => {
                // A bare identifier argument is emitted as a string literal so
                // the generated Typst always compiles. Semantic resolution
                // against a function signature is the evaluator's job.
                let escaped = id.replace('\\', "\\\\").replace('"', "\\\"");
                self.push('"');
                self.push_str(&escaped);
                self.push('"');
            }
            IrValue::Content(nodes) => {
                self.push('[');
                for node in nodes {
                    self.lower_node(node);
                }
                self.push(']');
            }
        }
    }

    fn push(&mut self, ch: char) {
        self.output.push(ch);
    }

    fn push_str(&mut self, s: &str) {
        self.output.push_str(s);
    }
}

#[cfg(test)]
mod tests {
    use scribium_core::ir::{IrDocument, IrInline, IrListItem, IrMetadata, IrNode, IrValue};
    use scribium_core::source::SourceSpan;

    fn empty_span() -> SourceSpan {
        SourceSpan::new(scribium_core::SourceId(0), 0, 0)
    }

    fn text(text: &str) -> IrInline {
        IrInline::Text {
            content: text.to_string(),
            span: empty_span(),
        }
    }

    #[test]
    fn lower_empty_document() {
        let doc = IrDocument {
            nodes: vec![],
            metadata: IrMetadata::default(),
        };
        let (code, map) = super::lower_to_typst(&doc);
        assert_eq!(code, "");
        assert!(map.is_empty());
    }

    #[test]
    fn lower_heading_paragraph() {
        let doc = IrDocument {
            nodes: vec![
                IrNode::Heading {
                    level: 1,
                    content: vec![text("Hello")],
                    span: empty_span(),
                },
                IrNode::Paragraph {
                    content: vec![text("World")],
                    span: empty_span(),
                },
            ],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "= Hello\n\nWorld\n\n");
    }

    #[test]
    fn lower_heading_levels() {
        let doc = IrDocument {
            nodes: vec![
                IrNode::Heading {
                    level: 2,
                    content: vec![text("Section")],
                    span: empty_span(),
                },
                IrNode::Heading {
                    level: 3,
                    content: vec![text("Subsection")],
                    span: empty_span(),
                },
            ],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "== Section\n\n=== Subsection\n\n");
    }

    #[test]
    fn lower_emphasis_and_strong() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![
                    text("Hello "),
                    IrInline::Emphasis {
                        content: vec![text("italic")],
                        span: empty_span(),
                    },
                    text(" and "),
                    IrInline::Strong {
                        content: vec![text("bold")],
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "Hello *italic* and *bold*\n\n");
    }

    #[test]
    fn lower_code_block() {
        let doc = IrDocument {
            nodes: vec![IrNode::CodeBlock {
                language: Some("rust".into()),
                source: "fn main() {}".into(),
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "```rust\nfn main() {}\n```\n\n");
    }

    #[test]
    fn lower_unordered_list() {
        let doc = IrDocument {
            nodes: vec![IrNode::UnorderedList {
                items: vec![
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("Item one")],
                            span: empty_span(),
                        }],
                        span: empty_span(),
                    },
                    IrListItem {
                        nodes: vec![IrNode::Paragraph {
                            content: vec![text("Item two")],
                            span: empty_span(),
                        }],
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "- Item one\n\n- Item two\n\n\n");
    }

    #[test]
    fn lower_thematic_break() {
        let doc = IrDocument {
            nodes: vec![IrNode::ThematicBreak { span: empty_span() }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "---\n\n");
    }

    #[test]
    fn lower_inline_directive_call() {
        let doc = IrDocument {
            nodes: vec![IrNode::Paragraph {
                content: vec![
                    text("Look: "),
                    IrInline::DirectiveCall {
                        name: "strong".into(),
                        positional_args: vec![],
                        named_args: vec![],
                        body: Some(vec![text("emphasized")]),
                        span: empty_span(),
                    },
                ],
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "Look: #strong[emphasized]\n\n");
    }

    #[test]
    fn lower_block_directive_call() {
        let doc = IrDocument {
            nodes: vec![IrNode::FunctionCall {
                name: "figure".into(),
                positional_args: vec![],
                named_args: vec![("kind".into(), IrValue::String("table".into()))],
                body: Some(vec![IrNode::Paragraph {
                    content: vec![text("content")],
                    span: empty_span(),
                }]),
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "#figure(kind: \"table\")[content\n]\n\n");
    }

    #[test]
    fn lower_math_inline() {
        let doc = IrDocument {
            nodes: vec![IrNode::Math {
                source: "E = mc^2".into(),
                display: false,
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "$E = mc^2$\n");
    }

    #[test]
    fn lower_math_display() {
        let doc = IrDocument {
            nodes: vec![IrNode::Math {
                source: "x = (-b pm sqrt(b^2 - 4ac)) / (2a)".into(),
                display: true,
                span: empty_span(),
            }],
            metadata: IrMetadata::default(),
        };
        let code = super::lower_to_typst_code(&doc);
        assert_eq!(code, "$ x = (-b pm sqrt(b^2 - 4ac)) / (2a) $\n\n");
    }
    #[test]
    fn source_map_is_independent_of_source_insertion_order() {
        use scribium_core::{compile, CompileOptions, VirtualProjectBuilder};

        let project1 = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("a.qd", "content a")
            .expect("valid path")
            .add_source("b.qd", "content b")
            .expect("valid path")
            .add_source("main.qd", "# Main\n\n{{ a.qd }} {{ b.qd }}")
            .expect("valid path")
            .build()
            .unwrap();

        let project2 = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("b.qd", "content b")
            .expect("valid path")
            .add_source("a.qd", "content a")
            .expect("valid path")
            .add_source("main.qd", "# Main\n\n{{ a.qd }} {{ b.qd }}")
            .expect("valid path")
            .build()
            .unwrap();

        let result1 = compile(&project1, &CompileOptions::default());
        let result2 = compile(&project2, &CompileOptions::default());

        // Lower to Typst with source maps
        let (typst1, map1) = super::lower_to_typst(&result1.ir);
        let (typst2, map2) = super::lower_to_typst(&result2.ir);

        // Generated Typst should be identical
        assert_eq!(typst1, typst2);

        // Source maps should be identical
        assert_eq!(map1, map2);
    }

    #[test]
    fn conditional_evaluation_before_lowering() {
        use crate::lower_to_typst_code;
        use scribium_core::{compile, CompileOptions, VirtualProjectBuilder};

        // .if {true} block body -> kept, no #if in output
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", ".if {true}\n    kept\n")
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        let typst = lower_to_typst_code(&result.ir);
        assert!(result.diagnostics.is_empty());
        assert!(typst.contains("kept"));
        assert!(!typst.contains("#if"));

        // .if {false} -> dropped
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", ".if {false}\n    dropped\n")
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        let typst = lower_to_typst_code(&result.ir);
        assert!(result.diagnostics.is_empty());
        assert!(!typst.contains("dropped"));

        // .ifnot {no} -> kept
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", ".ifnot {no}\n    kept\n")
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        let typst = lower_to_typst_code(&result.ir);
        assert!(result.diagnostics.is_empty());
        assert!(typst.contains("kept"));

        // Inline .if {true} {text}
        let project = VirtualProjectBuilder::new()
            .entry("main.qd")
            .expect("valid path")
            .add_source("main.qd", "before .if {true} {inline} after\n")
            .expect("valid path")
            .build()
            .unwrap();
        let result = compile(&project, &CompileOptions::default());
        let typst = lower_to_typst_code(&result.ir);
        assert!(result.diagnostics.is_empty());
        assert!(typst.contains("before"));
        assert!(typst.contains("inline"));
        assert!(typst.contains("after"));
        assert!(!typst.contains("#if"));
    }
}
